extends Label

#func _input(event):
#	if Input.is_action_just_pressed("f3"): visible = !visible

func _physics_process(delta):
	text = "fps: " + str(Engine.get_frames_per_second())
	text += "\n"
	text += 'mem: ' + String.humanize_size(OS.get_static_memory_usage())
	text += "\n"
	text += 'vram: ' + String.humanize_size(Performance.get_monitor(20))
	text += "\n"
#	if has_node(singleton.player_path):
#		text += 'x: ' + str(int(get_node(singleton.player_path).global_position.x))
#		text += "\n"
#		text += 'y: ' + str(int(get_node(singleton.player_path).global_position.y))

