extends TouchScreenButton

onready var initpos = global_position
onready var initpos2 = global_position
var posswitch = true
var text = ''
var id = 0

var collayer = 4
func col():
	print(collayer)
	$col.collision_layer = collayer
	$col.collision_mask = collayer


func _physics_process(delta):
	$Label.text = text
	$Label.show()
	global_position = initpos if posswitch else initpos2
	if not posswitch: $Label.hide()
#	$col/CollisionShape2D.call_deferred('set_disabled', false)
	if is_pressed(): 
#		$col/CollisionShape2D.call_deferred('set_disabled', true)
		$Label.hide()
		global_position = get_global_mouse_position()


func _on_Button_mouse_entered():
	print('mouse in')
#	$Label.show()
	pass # Replace with function body.


func _on_Button_mouse_exited():
	print('mouse out')
#	$Label.hide()
	pass # Replace with function body.
