extends Node2D


# Declare member variables here. Examples:
# var a = 2
# var b = "text"
var button = preload("res://ui/Button.tscn")

# Called when the node enters the scene tree for the first time.
func _ready():
	for i in 5:
		var button2 = button.instance()
		add_child(button2)
		button2.initpos = global_position
		button2.initpos.y += i * 72
		button2.initpos.x += 270
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
